# Prometheus Alert Rules for Cyber Werewolves

groups:
  - name: cyber-werewolves-alerts
    rules:
      # API Service Alerts
      - alert: APIServiceDown
        expr: up{job="api"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "API service is down"
          description: "API service has been down for more than 1 minute"

      - alert: APIHighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High API error rate"
          description: "API error rate is {{ $value }} errors per second"

      - alert: APILatencyHigh
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High API latency"
          description: "95th percentile API latency is {{ $value }} seconds"

      # Agent Service Alerts
      - alert: AgentServiceDown
        expr: up{job="agents"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Agent service is down"
          description: "Agent service has been down for more than 1 minute"

      - alert: AgentTimeoutRateHigh
        expr: rate(agent_timeouts_total[5m]) > 0.05
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High agent timeout rate"
          description: "Agent timeout rate is {{ $value }} per second"

      # WebSocket Gateway Alerts
      - alert: WebSocketGatewayDown
        expr: up{job="websocket-gateway"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "WebSocket gateway is down"
          description: "WebSocket gateway has been down for more than 30 seconds"

      - alert: WebSocketConnectionsHigh
        expr: websocket_connections_total > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High WebSocket connections"
          description: "WebSocket connections count is {{ $value }}"

      # Database Alerts
      - alert: PostgreSQLDown
        expr: up{job="postgres"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "PostgreSQL is down"
          description: "PostgreSQL has been down for more than 1 minute"

      - alert: PostgreSQLSlowQueries
        expr: rate(pg_stat_database_calls_total[5m]) > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "PostgreSQL slow queries"
          description: "PostgreSQL has {{ $value }} slow queries per second"

      # Redis Alerts
      - alert: RedisDown
        expr: up{job="redis"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Redis is down"
          description: "Redis has been down for more than 1 minute"

      - alert: RedisMemoryHigh
        expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Redis memory usage high"
          description: "Redis memory usage is {{ $value | humanizePercentage }}"

      # NATS Alerts
      - alert: NATSDown
        expr: up{job="nats"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "NATS is down"
          description: "NATS has been down for more than 1 minute"

      # System Alerts
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value }}%"

      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value }}%"

      - alert: LowDiskSpace
        expr: (1 - (node_filesystem_avail_bytes / node_filesystem_size_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Low disk space"
          description: "Disk usage is {{ $value }}%"